function [] = make_sysinfo(sysinfo,skip_remake_shift,cpath, pth_irf, irfname, pth_wigs,...
            wigsname, pth_ext, extname, data_shift_name, pth_data_for_shift,shift)

if exist([cpath,'SysInfo.txt'],'file')==2
    cppout = fopen([cpath,'SysInfo.txt'],'r+');
    [old_filenames, count] = fscanf(cppout, '%s');
    fclose(cppout);
else
    old_filenames = 'sysinfo did not exist';
end

if ~strcmp(old_filenames,'sysinfo did not exist') && skip_remake_shift
else
    new_filenames = [pth_irf, irfname, pth_wigs, wigsname,...
        pth_ext,extname, pth_data_for_shift, data_shift_name,...
        num2str(shift.step),num2str(shift.min),num2str(shift.max), ...
        num2str(shift.w2step),num2str(shift.w2min),num2str(shift.w2max),...
        num2str(shift.backstep),num2str(shift.backmin),num2str(shift.backmax)];
    
    if ~isequal(new_filenames,old_filenames) || sysinfo ~= 0;
        [~, ~, ~, ~, ~, ~, ~] = make_irf_wig_ext_minres(pth_irf, irfname, pth_wigs,...
            wigsname, pth_ext, extname, data_shift_name, pth_data_for_shift,...
            shift.step, shift.min, shift.max, shift.w2step, shift.w2min,...
            shift.w2max, shift.backstep, shift.backmin, shift.backmax);
        
        fileID = fopen([cpath,'SysInfo.txt'],'w');
        fprintf(fileID,'%s%s\n%s%s\n%s%s\n%s%s\n',pth_irf, ...
            irfname, pth_wigs, wigsname, pth_ext,extname,pth_data_for_shift,...
            data_shift_name,num2str(shift.step),num2str(shift.min),num2str(shift.max),...
            num2str(shift.w2step), num2str(shift.w2min),num2str(shift.w2max),...
            num2str(shift.backstep),num2str(shift.backmin),num2str(shift.backmax));
        fclose(fileID);
    end
end

end